
apply from: './gradle/libraries.gradle'

buildscript {
    ext {
        hiltVersion = '2.44'
        gitPluginVersion = '2.0.0'
        kotlinPluginVersion = '1.7.20'
        objectboxPluginVersion = '2.9.1'
        androidToolsPluginVersion = '7.3.1'
        googleServicesPluginVersion = '4.3.10'
        googlePlayPublisherPluginVersion = '3.8.6'
    }
    repositories {
        google()
        mavenCentral()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
    dependencies {
        classpath "com.github.triplet.gradle:play-publisher:${googlePlayPublisherPluginVersion}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinPluginVersion"
        classpath "io.objectbox:objectbox-gradle-plugin:${objectboxPluginVersion}"
        classpath "com.google.gms:google-services:${googleServicesPluginVersion}"
        classpath "com.android.tools.build:gradle:${androidToolsPluginVersion}"
        classpath "com.google.dagger:hilt-android-gradle-plugin:${hiltVersion}"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        classpath 'com.google.firebase:firebase-plugins:2.0.0'
        classpath "org.ajoberstar:grgit:${gitPluginVersion}"
        // classpath 'com.akaita.android:easylauncher:1.3.1'
        classpath('net.sf.proguard:proguard-gradle:6.0.3') { force = true }
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
        maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
    }
}

subprojects {
    task allDeps(type: DependencyReportTask) {}
    configurations.all {
        resolutionStrategy {
            force 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1'
            force 'androidx.lifecycle:lifecycle-runtime-ktx:2.5.1'
            force 'androidx.lifecycle:lifecycle-livedata-ktx:2.5.1'
            force 'androidx.lifecycle:lifecycle-viewmodel:2.5.1'
            force 'androidx.lifecycle:lifecycle-runtime:2.5.1'
            force 'androidx.activity:activity:1.5.1'
            force 'androidx.activity:activity-ktx:1.5.1'
            force 'androidx.fragment:fragment:1.5.1'
            force 'androidx.fragment:fragment-ktx:1.5.1'
        }
    }
}

task clean(type: Delete, group: 'build') {
    delete rootProject.buildDir
}

def incrementModuleVersion(moduleName, moduleVersion) {
    def branch = getProjectCurrentBranch()
    println "incrementModuleVersion: $moduleName -> $branch -> $moduleVersion"
    def tagName = "$moduleName/$moduleVersion"
    try {
        def git = org.ajoberstar.grgit.Grgit.open(dir: project.rootDir.absolutePath)
        git.commit(message: "[ci skip][gradle] increment module version: ${tagName}", all: true)
        git.push(all: false, tags: false)
        git.tag.add(name: tagName, force: true, message: "[ci skip][gradle] increment module version: ${tagName}")
        git.push(refsOrSpecs: ["${tagName}"])
    } catch (Exception e) {
        println "Failed to increment Git module version: ${e.message}."
    }
}

def getProjectCurrentBranch() {
    try {
        def git = org.ajoberstar.grgit.Grgit.open(dir: project.rootDir.absolutePath)
        def branch = git.branch.current().getName()
        return branch
    } catch (Exception e) {
        println "Failed to open Git repository: ${e.message}. Defaulting branch to 'master'."
        return 'master'
    }
}

def getProjectVersionUpdateStrategy() {
    def key = 'PROJECT_VERSION_UPDATE_STRATEGY'
    def value = System.getProperty(key, null)
    if (value != null) {
        println "take from cache"
        return value
    }
    try {
        def git = org.ajoberstar.grgit.Grgit.open(dir: project.rootDir.absolutePath)
        def lastCommit = git.head()
        def commitMessage = lastCommit.shortMessage
        def pattern = java.util.regex.Pattern.compile("Merge branch '(.*)'.*");
        def matcher = pattern.matcher(commitMessage);
        def matches = matcher.matches()
        if (!matches) {
            pattern = java.util.regex.Pattern.compile("^\\[(.*)\\].*");
            matcher = pattern.matcher(commitMessage);
            matches = matcher.matches()
        }
        if (matches) {
            def mergedBranch = matcher.group(1).toLowerCase()
            println "merge -> ${mergedBranch}"
            if (mergedBranch.startsWith('stage')) {
                value = ''
            } else if (mergedBranch.startsWith('dev')) {
                value = ''
            } else if (mergedBranch.startsWith('snapshot')) {
                value = ''
            } else if (mergedBranch.startsWith('release')) {
                value = 'major'
            } else if (mergedBranch.startsWith('feature')) {
                value = 'minor'
            } else if (mergedBranch.startsWith('bugfix')) {
                value = 'patch'
            } else {
                value = 'patch'
            }
        } else {
            value = 'patch'
        }
    } catch (Exception e) {
        println "Failed to determine update strategy via Git: ${e.message}. Defaulting to 'patch'."
        value = 'patch'
    }

    if (value == null) {
        value = 'patch'
    }

    System.setProperty(key, value)
    return value
}

task unitTests
task integrationTests
task testDebugUnitTest
