apply from: './gradle/libraries.gradle'

buildscript {
    ext {
        hiltVersion = '2.38.1'
        gitPluginVersion = '2.0.0'
        kotlinPluginVersion = '1.5.30'
        objectboxPluginVersion = '2.9.0'
        androidToolsPluginVersion = '4.0.2'
        googleServicesPluginVersion = '4.3.10'
        googlePlayPublisherPluginVersion = '2.6.2'
    }
    repositories {
        google()
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url 'https://google.bintray.com/exoplayer/' }
        maven { url 'https://dl.bintray.com/android/android-tools' }
        maven { url 'https://dl.bintray.com/firebase/gradle/' }
    }
    dependencies {
        classpath "com.github.triplet.gradle:play-publisher:${googlePlayPublisherPluginVersion}"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinPluginVersion"
        classpath "io.objectbox:objectbox-gradle-plugin:${objectboxPluginVersion}"
        classpath "com.google.gms:google-services:${googleServicesPluginVersion}"
        classpath "com.android.tools.build:gradle:${androidToolsPluginVersion}"
        classpath "com.google.dagger:hilt-android-gradle-plugin:${hiltVersion}"
        classpath 'com.google.firebase:firebase-crashlytics-gradle:2.8.1'
        classpath 'com.google.firebase:firebase-plugins:2.0.0'
        classpath "org.ajoberstar:grgit:${gitPluginVersion}"
        classpath 'com.akaita.android:easylauncher:1.3.1'
        classpath('net.sf.proguard:proguard-gradle:6.0.3') { force = true }
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://jitpack.io' }
        maven { url 'https://zendesk.jfrog.io/zendesk/repo' }
    }
}

subprojects {
    task allDeps(type: DependencyReportTask) {}
}

task clean(type: Delete, group: 'build') {
    delete rootProject.buildDir
}

def incrementModuleVersion(moduleName, moduleVersion) {
    def branch = getProjectCurrentBranch()
    println "incrementModuleVersion: $moduleName -> $branch -> $moduleVersion"
    def tagName = "$moduleName/$moduleVersion"
    def git = org.ajoberstar.grgit.Grgit.open(dir: project.rootDir.absolutePath)
    git.commit(message: "[ci skip][gradle] increment module version: ${tagName}", all: true)
    git.push(all: false, tags: false)
    git.tag.add(name: tagName, force: true, message: "[ci skip][gradle] increment module version: ${tagName}")
    git.push(refsOrSpecs: ["${tagName}"])
}

def getProjectCurrentBranch() {
    def git = org.ajoberstar.grgit.Grgit.open(dir: project.rootDir.absolutePath)
    def branch = git.branch.current().getName()
    return branch
}

def getProjectVersionUpdateStrategy() {
    def key = 'PROJECT_VERSION_UPDATE_STRATEGY'
    def value = System.getProperty(key, null)
    if (value != null) {
        println "take from cache"
        return value
    }
    def git = org.ajoberstar.grgit.Grgit.open(dir: project.rootDir.absolutePath)
    def lastCommit = git.head()
    def commitMessage = lastCommit.shortMessage
    def pattern = java.util.regex.Pattern.compile("Merge branch '(.*)'.*");
    def matcher = pattern.matcher(commitMessage);
    def matches = matcher.matches()
    if (!matches) {
        pattern = java.util.regex.Pattern.compile("^\\[(.*)\\].*");
        matcher = pattern.matcher(commitMessage);
        matches = matcher.matches()
    }
    if (matches) {
        def mergedBranch = matcher.group(1).toLowerCase()
        println "merge -> ${mergedBranch}"
        if (mergedBranch.startsWith('stage')) {
            value = ''
        } else if (mergedBranch.startsWith('dev')) {
            value = ''
        } else if (mergedBranch.startsWith('snapshot')) {
            value = ''
        } else if (mergedBranch.startsWith('release')) {
            value = 'major'
        } else if (mergedBranch.startsWith('feature')) {
            value = 'minor'
        } else if (mergedBranch.startsWith('bugfix')) {
            value = 'patch'
        } else {
            value = 'patch'
        }
    } else {
        value = 'patch'
    }

    if (value == null) {
        throw new Exception("Unknown merge commit type (message: '$commitMessage'). Please use default convention 'bugfix/feature/release'")
    }

    System.setProperty(key, value)
    return value
}

task unitTests
task integrationTests
task testDebugUnitTest
