ext {
    androidLibraryGroup = 'com.wb.android'

    androidBuildToolsVersion = '33.0.0'
    androidCompileSdkVersion = 33
    androidTargetSdkVersion = 30
    androidMinSdkVersion = 21

    androidVersionMajor = 0
    androidVersionMinor = 0
    androidVersionPatch = 0

    mavenReleasesRepo = 'https://mymavenrepo.com/repo/Ufh9uXJUcHoS1feAY0bx/'
    mavenReleasesUsername = ''
    mavenReleasesPassword = ''

    mavenSnapshotsRepo = 'https://mymavenrepo.com/repo/Ufh9uXJUcHoS1feAY0bx/'
    mavenSnapshotsUsername = ''
    mavenSnapshotsPassword = ''
}
